language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
before_script:
- "echo $JAVA_OPTS"
- "export JAVA_OPTS=-Xmx2048m"

script:
- mvn clean install -DskipTests=false -f ./dhis-2/pom-full.xml

cache:
  directories:
  - $HOME/.m2
  
branches:
  only:
  - master
  - /^2\.[0-9]{1,}/
